name: Dart Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Dart SDK
      uses: dartsdk/setup-dart@v2
      with:
        sdk: stable
    - name: Get dependencies
      run: pub get
    - name: Run tests
      run: pub run test
