name: Dart CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dart
      uses: actions/setup-dart

    - name: Test with Dart
      run: dart test.dart
