name: Dart Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        dart-version: '2.14.4'
    - name: Install dependencies
      run: dart pub get
    - name: Run tests
      run: dart test
